Refine the style of documentation in Part I
pietvo/fancyhdr pull request #16
Opened 2024-05-02 05:02 UTC by SwitWu

This PR is aimed to refine the style of documentation in Part I. To be more precise, the first item in the margin area is vertically aligned with its description area. For the effect, please see the attached PDF file: [fancyhdr.pdf](https://github.com/pietvo/fancyhdr/files/15183960/fancyhdr.pdf)

2024-05-02 05:03 UTC, SwitWu commented on fancyhdr.dtx
> -%
I think this part is unnecessary so I deleted it.

2024-05-03 09:20 UTC, pietvo requested changes
This looks good. Only for cosmetic reasons I would prefer to put the `DescribeMacro` before the macro it describes.

2024-05-03 09:28 UTC, SwitWu commented
>  put the `DescribeMacro` before the macro it describes.

Done.

2024-05-03 11:10 UTC, pietvo approved these changes

2024-05-03 14:55 UTC, merged